# Generated by Django 5.1.5 on 2025-05-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_artiles_options_artiles_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='full_text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='artiles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='.media/images/'),
        ),
    ]
